import tkinter as tk
import tkinter as ttk
from tkinter import messagebox
s=tk.Tk()
s.title("Login page")
s.geometry("500x500")
s.config(bg="black")
def logi():
    username=entry1.get()
    passw=entry2.get()
    if username=="sanjith" and passw=="1311":
        messagebox.showinfo("showinfo", "Logined succesfull")
        w=ttk.Toplevel(s)
        w.title("calculator")
        w.geometry("500x500")
        w.config(bg="black")
        button1=ttk.Button(w,text="ADD",font=("bold",40),width="8",height="3",command=add)
        button1.grid(row=2,column=2)
        button2=ttk.Button(w,text="SUB",font=("bold",40),width="8",height='3',command=sub)
        button2.grid(row=2,column=3)
        button3=ttk.Button(w,text="MULT",font=("bold",40),width="8",height="3",command=mul)
        button3.grid(row=3,column=2)
        button4=ttk.Button(w,text="DIV",font=("bold",40),width="8",height="3",command=div)
        button4.grid(row=3,column=3)
        button12=tk.Button(w,text="close",font="bold",bd=5,command=w.destroy)
        button12.grid(row=4,columnspan=3)
        
    else:
        messagebox.showerror("showerror", "Error")




def add():
    def c1():
        n1=e1.get()
        n2=e2.get()
        ans=int(n1)+int(n2)
        l2.config(text=ans)
    a=tk.Tk()
    a.title="add"
    a.geometry("500x500")
    label10=tk.Label(a,text="",font=("bold",80))
    label10.grid(row=0,column=0)
    label11=tk.Label(a,text="enter the first number",)
    label11.grid(row=1,column=3)
    e1=tk.Entry(a,bd=10,cursor="arrow")
    e1.grid(row=1,column=4)
    label12=tk.Label(a,text="enter the second number",)
    label12.grid(row=2,column=3)
    e2=tk.Entry(a,bd=10,cursor="arrow")
    e2.grid(row=2,column=4)
    l1=tk.Label(a,text="Result=",width="5")
    l1.grid(row=4,column=3)
    l2=tk.Label(a,width="8")
    l2.grid(row=4,column=4)
    button11=tk.Button(a,text="add",font="bold",bd=5,command=c1)
    button11.grid(row=3,column=4)
    button12=tk.Button(a,text="close",font="bold",bd=5,command=a.destroy)
    button12.grid(row=4,column=6)
    button13=tk.Button(a,text="close all",font="bold",bd=5,command=s.destroy)
    button13.grid(row=5,column=6)
    

def sub():
    def c2():
        n1=e1.get()
        n2=e2.get()
        ans=int(n1)-int(n2)
        l2.config(text=ans)
    a=tk.Tk()
    a.title="sub"
    a.geometry("500x500")
    label10=tk.Label(a,text="",font=("bold",80))
    label10.grid(row=0,column=0)
    label11=tk.Label(a,text="enter the first number",)
    label11.grid(row=1,column=3)
    e1=tk.Entry(a,bd=10,cursor="arrow")
    e1.grid(row=1,column=4)
    label12=tk.Label(a,text="enter the second number",)
    label12.grid(row=2,column=3)
    e2=tk.Entry(a,bd=10,cursor="arrow")
    e2.grid(row=2,column=4)
    l1=tk.Label(a,text="Result=")
    l1.grid(row=4,column=3)
    l2=tk.Label(a)
    l2.grid(row=4,column=4)
    button11=tk.Button(a,text="sub",font="bold",bd=5,command=c2)
    button11.grid(row=3,column=4)
    button12=tk.Button(a,text="close",font="bold",bd=5,command=a.destroy)
    button12.grid(row=4,column=6)
    button13=tk.Button(a,text="close all",font="bold",bd=5,command=s.destroy)
    button13.grid(row=5,column=6)
    

def mul():
    def c1():
        n1=e1.get()
        n2=e2.get()
        ans=int(n1)*int(n2)
        l2.config(text=ans)
    a=tk.Tk()
    a.title="multiplication"
    a.geometry("500x500")
    label10=tk.Label(a,text="",font=("bold",80))
    label10.grid(row=0,column=0)
    label11=tk.Label(a,text="enter the first number",)
    label11.grid(row=1,column=3)
    e1=tk.Entry(a,bd=10,cursor="arrow")
    e1.grid(row=1,column=4)
    label12=tk.Label(a,text="enter the second number",)
    label12.grid(row=2,column=3)
    e2=tk.Entry(a,bd=10,cursor="arrow")
    e2.grid(row=2,column=4)
    l1=tk.Label(a,text="Result=")
    l1.grid(row=4,column=3)
    l2=tk.Label(a)
    l2.grid(row=4,column=4)
    button11=tk.Button(a,text="multiply",font="bold",bd=5,command=c1)
    button11.grid(row=3,column=4)
    button12=tk.Button(a,text="close",font="bold",bd=5,command=a.destroy)
    button12.grid(row=4,column=6)
    button13=tk.Button(a,text="close all",font="bold",bd=5,command=s.destroy)
    button13.grid(row=5,column=6)
    

def div():
    def c1():
        n1=e1.get()
        n2=e2.get()
        ans=int(n1)/int(n2)
        l2.config(text=ans)
    a=tk.Tk()
    a.title="division"
    a.geometry("500x500")
    label10=tk.Label(a,text="",font=("bold",80))
    label10.grid(row=0,column=0)
    label11=tk.Label(a,text="enter the first number",)
    label11.grid(row=1,column=3)
    e1=tk.Entry(a,bd=10,cursor="arrow")
    e1.grid(row=1,column=4)
    label12=tk.Label(a,text="enter the second number",)
    label12.grid(row=2,column=3)
    e2=tk.Entry(a,bd=10,cursor="arrow")
    e2.grid(row=2,column=4)
    l1=tk.Label(a,text="Result=")
    l1.grid(row=4,column=3)
    l2=tk.Label(a)
    l2.grid(row=4,column=4)
    button11=tk.Button(a,text="divde",font="bold",bd=5,command=c1)
    button11.grid(row=3,column=4)
    button12=tk.Button(a,text="close",font="bold",bd=5,command=a.destroy)
    button12.grid(row=4,column=6)
    button13=tk.Button(a,text="close all",font="bold",bd=5,command=s.destroy)
    button13.grid(row=7,column=6)
    


    
label1=tk.Label(s,text="LOGIN TO CONTINUE",font="bold",bg="black",fg="white")
label1.grid()
label2=tk.Label(s,text="User Name",bg="black",fg="white")
label2.grid(row=1,column=1)
entry1=tk.Entry(s,bd=5)
entry1.grid(row=1,column=2)
label3=tk.Label(s,text="Password",bg="black",fg="white")
label3.grid(row=2,column=1)
entry2=tk.Entry(s,show="*",bd=5)
entry2.grid(row=2,column=2)
button=tk.Button(s,text="LOGIN",font="bold",bd=5,command=logi)
button.grid(row=3,column=2,columnspan=2)
button12=tk.Button(s,text="close",font="bold",bd=5,command=s.destroy)
button12.grid(row=10,column=4)
s.mainloop()